---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Restart smbd
  ansible.builtin.systemd:
    name: smbd
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart avahi-daemon
  ansible.builtin.systemd:
    name: avahi-daemon
    state: restarted

- name: Restart file server rsync timers
  ansible.builtin.systemd:
    name: "rsync-{{ item.name }}.timer"
    state: restarted
  loop: "{{ file_server_rsync_jobs }}"
  loop_control:
    label: "{{ item.name }}"
